require "sequitur"

class Grammar
  attr_accessor :rules, :start
  def initialize()
    # string
    @start = nil
    # string -> (GSymbol array) map
    @rules = {}
  end
  def addRule(left,right)
    @rules[left] = right
  end
  # returns the array of terminal symbols generated by curVar : string
  def expandVar(curVar)
    raise unless (curVar.class == String)
    curSeq = @rules[curVar]
    nextVarInd = curSeq.index {|sym| sym.isVar}
    # recursively replace variables until on terminals left
    until nextVarInd == nil
      #nextVar : string
      nextVar = curSeq[nextVarInd].token
      repText = expandVar(nextVar)
      curSeq = curSeq.map do |sym|
        if (sym.isVar && sym.token == nextVar)
          next repText
        else
          next sym
        end
      end
      curSeq = curSeq.flatten
      nextVarInd = curSeq.index {|sym| sym.isVar}
    end
    return curSeq
  end
  def to_s
    out = "Start: "+@start.to_s+"\n"
    @rules.each do |curLeft,curRight|
      out += (curLeft)+":>"+(curRight.to_s)+"\n"
    end
    return out
  end
end

class GSymbol
  attr_accessor :token, :isVar
  def initialize(isVar,token)
    @isVar = isVar
    @token = token
  end
  def to_s
    return @token
  end
end

# Converts from the linked-list CFG format used in sequitur to
# the array + dictionary CFG format here. Algorithm stolen from
# puts_grammar

def convert_seq(seqGrammar)
  newGramm = Grammar.new()

  curRules = [seqGrammar]
  nonterminals = {"*" => true}
  newGramm.start = "*"
  curRules.each do |rule|
    newVar = rule.token
    newSeq = []
    nextsym = rule.next
    until nextsym.is_head? do
      if not nextsym.rule.nil?
        curRules << nextsym.rule if not nonterminals[nextsym.token]
        nonterminals[nextsym.token] = true
        newSeq << GSymbol.new(true,nextsym.token)
      else
        newSeq << GSymbol.new(false,nextsym.token)
      end
      nextsym = nextsym.next
    end
    newGramm.addRule(newVar,newSeq)
  end
  return newGramm
end

str = "aactgaacatgagagacatagagacag"
gramm1 = Sequitur.new(str).run
myGrammar = convert_seq(gramm1)
puts myGrammar.expandVar("*").to_s
